# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnFq8AnTuc2_hXJ8MIRKXqgeTxkVZw7Z
"""

import tensorflow as tf
from tensorflow.keras import layers, models

def crear_red_simple(input_shape):
    """
    Crea una red neuronal simple (Perceptrón) para clasificación.
    Recibe: input_shape (número de columnas de X)
    Devuelve: El modelo compilado
    """
    model = models.Sequential([
        # Capa de entrada con el número de variables de tu X
        layers.Input(shape=(input_shape,)),

        # Capa de salida: 3 neuronas (una por cada riesgo: Low, Medium, High)
        # Usamos 'softmax' porque es clasificación multiclase
        layers.Dense(3, activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    return model