# -*- coding: utf-8 -*-
"""modelo_complejos5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdULN1OBuiyB2YqzGsEzTWM2N1JNv-Tm
"""

import tensorflow as tf
from tensorflow.keras import layers, models

def crear_modelo(input_shape):
    """
    Arquitectura Profunda, Ancha y con Regularización Doble
    """
    model = models.Sequential([
        layers.Input(shape=(input_shape,)),
        layers.Dense(64, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(32, activation='relu'),
        layers.Dense(16, activation='relu'),
        layers.Dropout(0.2),
        layers.Dense(3, activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model