# -*- coding: utf-8 -*-
"""modelo_complejos3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQnV3ZHFY2K9DA8KZ0tXFCOsBXhB7Mes
"""

import tensorflow as tf
from tensorflow.keras import layers, models

def crear_modelo(input_shape):
  """
  Crea una red neuronal profunda y estrecha.
  """
    model = models.Sequential([
        layers.Input(shape=(input_shape,)),
        layers.Dense(16, activation='relu'),
        layers.Dense(12, activation='relu'),
        layers.Dense(8, activation='relu'),
        layers.Dense(4, activation='relu'),
        layers.Dense(3, activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model