# -*- coding: utf-8 -*-
"""modelo_complejos1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmsqQlDG0uoBjYZIC8rc5WLdhhjDDqL9
"""

import tensorflow as tf
from tensorflow.keras import layers, models

def crear_modelo(input_shape):
    model = models.Sequential([
        layers.Input(shape=(input_shape,)),
        layers.Dense(32, activation='relu'),
        layers.Dense(16, activation='relu'),
        layers.Dense(3, activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model