# -*- coding: utf-8 -*-
"""modelo_complejos4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZYBx0PSUKj6qkrP7PRvP6nx_ablUB4K
"""

import tensorflow as tf
from tensorflow.keras import layers, models

def crear_modelo(input_shape):
    """
    Arquitectura Ancha y Superficial
    """
    model = models.Sequential([
        layers.Input(shape=(input_shape,)),
        layers.Dense(128, activation='relu'),
        layers.Dense(64, activation='relu'),
        layers.Dense(3, activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model
